## Configuration Settings for Sonic Screwdriver

# Should Sonic Screwdriver print out extra log messages?
# This option is helpful when reporting bugs or errors.
debug-mode: false

# Which permission will be required to use the sonic screwdriver item?
# This permission is NOT given to OPs by default.
# Default: "sonic.screwdriver"
permission: "sonic.screwdriver"

# What should the item look like for the sonic screwdriver?
# If you know how to serialize ItemStacks you can use that as a value as well.
item:
  material: BLAZE_ROD
  quantity: 1
  damage: 0
  custom-model-data: 14
