## Configuration Settings for Sonic Screwdriver

# Should Sonic Screwdriver print out extra log messages?
# This option is helpful when reporting bugs or errors.
debug-mode: false

# Which permission will be required to use the sonic screwdriver item?
# This permission is NOT given to OPs by default.
permission:
  name: "sonic.screwdriver"
  description: "Grants the ability to use sonic screwdriver items."
  default: OP

# What should the item look like for the sonic screwdriver?
# If you know how to serialize ItemStacks you can use that as a value as well.
item:
  material: BLAZE_ROD
  custom-model-data: "sonic.screwdriver"
  display-name: "<yellow>Sonic Screwdriver</yellow>"
  lore:
    - "<dark_purple>Doctor Who!</dark_purple>"
    - "<gray><italic>Allons-y!!</italic></gray>"

abilities:
  open-doors: true
  light-nether-portal: true
  instant-break-blocks: true
  overpowered-tnt: true

instant-break-block-types:
  - COBWEB
  - LADDER
  - VINE

sound:
  sound: "sonic:sonic.screwdriver"
  category: "player"
  volume: 1.0
  pitch: 2.0
