# Should the plugin be allowed to check for updates?
update-checker: true

# Configuration Settings
options:
  # What sound packet should be sent to the player when they use a sonic screwdriver?
  # If you have a resource pack with custom sounds you can also use those.
  # Default: "sonic.screwdriver"
  sound: "sonic.screwdriver"

  # Which permission will be required to use the sonic screwdriver item?
  # This permission is NOT given to OPs by default.
  # Default: "sonic.screwdriver"
  permission: "sonic.screwdriver"

  # What should the item look like for the sonic screwdriver?
  # If you know how to serialize ItemStacks you can use that as a value as well.
  # Default: Blaze Rod with name "&fSonic Screwdriver" and lore ["&5Doctor Who!", "&7&oAllons-y!!"]
  item:
    material: BLAZE_ROD
    quantity: 1
    damage: 0
    display-name: "&fSonic Screwdriver"
    lore:
      - "&5Doctor Who!"
      - "&7&oAllons-y!!"

# Language Messages
language:
  action-bar: "Whirr!"
  not-player: "&cOnly players can execute this command."
  invalid-target: "&cThat player is not online or does not exist."
  successful-give: "&cYou gave a sonic screwdriver to &7{target}&a."
  give-sonic: "&aYou are now The Doctor!"
